[package]
name = "misc_stuff"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "Some functions"
repository.workspace = true
license.workspace = true

[dependencies]
log.workspace = true
simple_logger.workspace = true

[lib]
